### ISSUE TITLE
bug: input with label wrong html code

### ISSUE THREAD

**Issue by michaelcozzolino** [themeselection/flyonui#15]
### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://flyonui.com/docs/forms/file-input/#label
### Describe your issue

the snippet provided, even if fully working is not completely right:

```
<label class="form-control w-96">
  <div class="label">
    <span class="label-text">Full name</span>
  </div>
  <input type="text" placeholder="John Doe" class="input" />
</label>
```

should be 
```
<div class="form-control w-96">
  <label class="label">
    <span class="label-text">Full name</span>
  </label>
  <input type="text" placeholder="John Doe" class="input" />
</div>
```

some other snippets are affected as well.

**Comment by OmkarOza** [comment]
Hi @michaelcozzolino,

Thank you for your feedback. The reason we used the first method, wrapping the entire form control in a `<label>`, was to handle a more complex layout. This approach ensures that all label-related elements, including additional spans and helper texts, are directly tied to the input field, allowing for a seamless user experience. It also enhances click behavior, making any part of the label area focus the input, and simplifies the HTML structure by avoiding redundant `for` and `id` attributes.

**Comment by michaelcozzolino** [comment]
understood, but according to the html specification that html you used is not valid as described [here](https://stackoverflow.com/questions/18609554/is-div-inside-label-block-correct#:~:text=No%2C%20HTML%20does%20not%20allow,and%20no%20descendant%20label%20elements.) 

furthermore according to your reason, both codes shown on the docs should be the same in terms of structure
![image](https://github.com/user-attachments/assets/fce28311-cbd7-4bf7-8707-4a749a9e45d1)
but they are not. is it wanted?

**Comment by yagnikvamja** [comment]
Hello @michaelcozzolino ,

Thank you for your valuable suggestion! We have incorporated your feedback and improved FlyonUI by adopting a consistent code structure across the library.

In specific cases, such as custom input fields, you may notice that the label is used as a wrapper. This approach ensures a larger clickable area, enhancing usability and accessibility.

We appreciate your continued support and insights!
