### ISSUE TITLE
bug: Animaiton not working in navbar when toggling the hamburger menu in mobile devices

### ISSUE THREAD

**Issue by SourishBiswas23** [themeselection/flyonui#18]
### What version of FlyonUI are you using?

1.1.0

### Which browsers are you seeing the problem on?

Chrome, Chrome Android, Firefox

### Reproduction URL

https://flyonui.com/docs/components/accordion/#basic-example

### Describe your issue

The animation while opening and closing the navbar is janky in every version of the navbar in the library. When the hamburger button is tapped in the closed navbar, the navbar opens up instantly and when it is tapped again, the icon on the navbar changes instantly but the navbar takes some time to close (duration-300 in the markup) resulting in jankiness. Looking at the code, I think that the navbar is supposed to decrease its height gracefully from the sum of the heights of its children to 0 and vice versa like that of the accordion.
[accordion.webm](https://github.c
[navbar.webm](https://github.com/user-attachments/assets/dfa32b11-29e2-4d31-be3b-a090a7c9302d)
om/user-attachments/assets/40378300-ec2d-49f0-9988-2fb2e2401493)
[accordionAndNavbar.webm](https://github.com/user-attachments/assets/4705b572-f94d-4ae9-bc72-7404c45aaf35)

**Comment by PruthviPraj00** [comment]
Hello @SourishBiswas23,

Thank you for bringing this issue to our attention. Please give us some time to resolve it; we plan to include the fix in the next release.

 Thank you for your patience!

**Comment by OmkarOza** [comment]
Hello @SourishBiswas23,

Thank you for your patience. We have successfully resolved the issue you encountered. You can now update the code from our site and continue using it without any further concerns.

Best regards.

**Comment by SourishBiswas23** [comment]
Thanks a lot.
