### ISSUE TITLE
BUG: Unable to use FlyonUI with Parcel

### ISSUE THREAD

**Issue by gavar** [themeselection/flyonui#22]
### What version of FlyonUI are you using?

v1.1.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://codesandbox.io/p/devbox/r5ml7v

### Describe your issue

Unable to build via Parcel using the default config.

Steps to reproduce:
- go to https://codesandbox.io/p/devbox/r5ml7v
- run `npm start`

```
> npx parcel src/index.html --no-cache

Port "1234" could not be used
Server running at http://localhost:35875
⠇ Building index.css...
⠴ Building index.css...
🚀   flyonui 1.1.0
├─ ✔︎ 2 themes added             https://flyonui.com/docs/themes
Server running at http://localhost:35875
🚨 Build failed.

@parcel/transformer-css: Invalid pseudo class after pseudo element, only user action pseudo classes (e.g. :hover, :active) are allowed

  /project/workspace/src/index.css:2243:30
    2242 | 
  > 2243 | .input::file-selector-button:disabled {
  >      |                              ^
    2244 |   background-color: var(--fallback-n,oklch(var(--n)/0.1));
    2245 | }
 ```

**Comment by OmkarOza** [comment]
Hello @gavar,

Thank you for reaching out. We’ve reviewed the issue you mentioned, but we're currently unable to access the link you provided. Could you please share a working link or, if possible, a zipped file of your local setup? This will allow us to assist you more effectively.

Awaiting your reply,

~Best regards

**Comment by gavar** [comment]
@OmkarOza sorry, it was set to private, please follow the same link again to see the project example: https://codesandbox.io/p/devbox/r5ml7v

this might be related to the latest SASS update as they are quite picky, it works okay with older SASS versions

**Comment by OmkarOza** [comment]
Hello @gavar,

I've reviewed your issue and identified that it originates from the input styling, which we have now fixed. This update will be included in the upcoming release, so please stay tuned.

Additionally, please note that this issue is unrelated to SASS, as there are no SASS files in your project.

~Best regards.
