### ISSUE TITLE
bug: vite build warning messages

### ISSUE THREAD

**Issue by pigochu** [themeselection/flyonui#26]
### What version of FlyonUI are you using?

v1.1.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://flyonui.com/framework-integrations/laravel/

### Describe your issue

I executed `npm vite build` using the instructions from the following URL and many warning messages occurred
https://flyonui.com/framework-integrations/laravel/

```
warnings when minifying css:
▲ [WARNING] Unexpected "*" [css-syntax-error]

    <stdin>:6515:76:
      6515 │ ... > .combo-box-selected\:active*:not(ul, .menu-title, .collaps...
           ╵                                  ^


▲ [WARNING] Unexpected "*" [css-syntax-error]

    <stdin>:6535:84:
      6535 │ ...cted .combo-box-selected\:menu*:not(ul, .menu-title, .collaps...
           ╵                                  ^


▲ [WARNING] Unexpected "*" [css-syntax-error]

    <stdin>:6554:76:
      6554 │ ... > .combo-box-selected\:active*:not(ul, .menu-title, .collaps...
           ╵                                  ^


▲ [WARNING] Unexpected "*" [css-syntax-error]

    <stdin>:6574:83:
      6574 │ ...ected.combo-box-selected\:menu*:not(ul, .menu-title, .collaps...
```

![image](https://github.com/user-attachments/assets/a9a335d7-911c-4b4a-9213-d48ea0dd937c)

Are these warning messages normal?

**Comment by OmkarOza** [comment]
Hello @pigochu,

Thank you for your patience. We have resolved the issue you were experiencing. Please update your package to FlyonUI v1.2.0 and continue using it without any concerns.

Best regards,

**Comment by pigochu** [comment]
@OmkarOza 
I upgrade to 1.2.0 , all input's placeholder and floating label will be hidden 
So I downgrade to 1.1.0 , It's works fine .
