### ISSUE TITLE
bug: Navbar Toggle Button Not Working On Svelte

### ISSUE THREAD

**Issue by refaldyrk** [themeselection/flyonui#5]
### What version of FlyonUI are you using?

stable

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

...

### Describe your issue

```js
<nav class="navbar rounded-box flex w-full gap-2 shadow max-md:flex-col md:items-center">
  <div class="flex w-full items-center justify-between">
    <div class="navbar-start items-center justify-between max-md:w-full">
      <a class="link text-base-content/90 link-neutral text-xl font-semibold no-underline" href="#">
        FlyonUI
      </a>
      <div class="md:hidden">
        <button type="button" class="collapse-toggle btn btn-outline btn-secondary btn-sm btn-square" data-collapse="#default-navbar-collapse" aria-controls="default-navbar-collapse" aria-label="Toggle navigation">
          <span class="icon-[tabler--menu-2] collapse-open:hidden size-4"></span>
          <span class="icon-[tabler--x] collapse-open:block hidden size-4"></span>
        </button>
      </div>
    </div>
  </div>
  <div id="default-navbar-collapse" class="md:navbar-end collapse hidden grow basis-full overflow-hidden transition-[height] duration-300 max-md:w-full">
    <ul class="menu md:menu-horizontal gap-2 p-0 text-base">
      <li><a href="#">Home</a></li>
      <li><a href="#">Services</a></li>
      <li><a href="#">Contact us</a></li>
    </ul>
  </div>
</nav>
```

On Mobile Screen The Navbar Not Working

**Comment by PruthviPraj00** [comment]
Hi @refaldyrk,

The navbar toggle button depends on the collapse plugin, so please ensure that the necessary JavaScript steps are included.

For your reference, you can consult the [quick start guide](https://flyonui.com/docs/getting-started/quick-start/).

We will soon release comprehensive documentation for Svelte.

Best regards.

**Comment by refaldyrk** [comment]
I have imported everything needed and have followed the documentation, yes there may be some adjustments in svelte, and I hope the developer can add documentation for svelte, because flyon is very awesome, I can't wait.

**Comment by PruthviPraj00** [comment]
Hello @refaldyrk,

We've updated our framework guide, and you can check it out here:

[https://flyonui.com/docs/getting-started/framework-guides/](https://flyonui.com/docs/getting-started/framework-guides/)

Additionally, you can explore the Svelte guide, which now includes a StackBlitz example:

[https://flyonui.com/framework-integrations/svelte/](https://flyonui.com/framework-integrations/svelte/)

Best regards.
