### ISSUE TITLE
docs: typo in `getting started > introduction`

### ISSUE THREAD

**Issue by MWleoB** [themeselection/flyonui#6]
### On which page do you see this issue?

https://flyonui.com/docs/getting-started/introduction/

### Describe the issue

![image](https://github.com/user-attachments/assets/462f9f66-bc38-4c8a-ac0c-4c65fb42559b)

Should be "semantic" instead of "sematic"

**Comment by PruthviPraj00** [comment]
Hello @MWleoB,

**Thank you for pointing that out!**

We appreciate your attention to detail. We will correct the typo from "sematic" to "semantic" in the documentation. The change should be reflected soon.

If you notice anything else or have further suggestions, feel free to reach out!

Best regards
