### ISSUE TITLE
docs: 官网显示没有样式

### ISSUE THREAD

**Issue by Dumbliidore** [themeselection/flyonui#8]
### On which page do you see this issue?

https://flyonui.com/

### Describe the issue

![image](https://github.com/user-attachments/assets/936972a2-e401-475b-a44d-67a7a595481a)
手机和电脑打开都是这样。还有打开的速度很慢。

### What browsers are you seeing the problem on?

Edge

**Comment by PruthviPraj00** [comment]
Hello @Dumbliidore,

Could you let me know the version of the browser you're using and your location when trying to access the link? I’m not experiencing any issues on my end. 

![Screenshot 2024-10-14 at 6 59 16 PM](https://github.com/user-attachments/assets/6d1d7e03-a237-4ccf-8cc3-ac45626f2a8a)

Could you please try testing it again?

Regards

**Comment by JCqiu** [comment]
你没有科学上网吧

**Comment by ajaypatelaj** [comment]
Hello @JCqiu 

We've redeployed our website and tested SSL and CDN.
Could you please try again and let us know?

If you are still facing the issue please share the Device, ISP, and Brower details.

**Comment by PruthviPraj00** [comment]
Hello @JCqiu,

I am closing this ticket. Feel free to reopen it or create a new one if you encounter further issues.
